### ISSUE TITLE
Please implement jumpTo(index) method

### ISSUE THREAD

**Issue by ahmedtanjim** [lucian1024/anchor_scroll_controller#6]
The scrollTo method is doing fine, but I have a very large list and it has about 4000 items and it takes forever to scroll. also, the height of the items is dynamic so I can't use jumpTo(value) method. so is there any way that I can use jumpTo(index)?

**Comment by lucian1024** [comment]
Unfortunately, there is currently no way to implement jumpTo(index) because flutter can not get the size of widget before the widget is layout. So we can not get the offset directly. Currently, we animate to the cached item and then the ListView will cache the next more items. And that's how we implement scrollTo(index).
